### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by damonsutherland** [istanbuljs/istanbuljs#123]
The following stack is presented in the html for the covered entity:

TypeError: Cannot read property 'start' of undefined
    at /home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-reports/lib/html/annotator.js:82:33
    at Array.forEach (native)
    at annotateFunctions (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-reports/lib/html/annotator.js:78:26)
    at Object.annotateSourceCode (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-reports/lib/html/annotator.js:189:9)
    at HtmlReport.onDetail (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-reports/lib/html/index.js:217:39)
    at Visitor.(anonymous function) [as onDetail] (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at Tree.visit (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-lib-report/lib/tree.js:158:20)
    at /home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-api/lib/reporter.js:84:18
    at Array.forEach (native)
    at Object.write (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/istanbul-api/lib/reporter.js:82:35)
    at browsers.forEach.browser (/home/ARBFUND/dsutherland/develop/@cw/hateoas/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:82:16)

[hateoas.zip](https://github.com/istanbuljs/istanbuljs/files/1577360/hateoas.zip)

**Comment by damonsutherland** [comment]
Note: I get similar stacks when generating other reports, i.e. lcovonly.

**Comment by gkemp94** [comment]
@damonsutherland Did you ever manage to get to the root of this issue? I'm experiencing the same issue. 

Thanks.

**Comment by loftyduck** [comment]
Looks like the same issue as #39

**Comment by bennyn** [comment]
I am also hitting the "Cannot read property 'start' of undefined" error but only when I try to combine reports from two sources. 

I have a `coverage-browser.json` file (created by Karma "lcov" reporter when running tests in a browser environment) and a `coverage-final.json`. I then merge both of them into a single HTML report using `nyc report` but when I view the HTML report I get the following error for most of the pages:

> Cannot read property 'start' of undefined 
> TypeError: Cannot read property 'start' of undefined     
at D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-reports\lib\html\annotator.js:92:34     
at Array.forEach ()     
at annotateFunctions (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-reports\lib\html\annotator.js:88:26)     
at Object.annotateSourceCode (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-reports\lib\html\annotator.js:239:9)     
at HtmlReport.onDetail (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-reports\lib\html\index.js:269:23)     
at Visitor.(anonymous function) [as onDetail] (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-lib-report\lib\tree.js:34:30)     
at ReportNode.Node.visit (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-lib-report\lib\tree.js:121:17)     
at D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-lib-report\lib\tree.js:114:23     
at Array.forEach ()    
 at visitChildren (D:\dev\projects\temp\karma-test\node_modules\nyc\node_modules\istanbul-lib-report\lib\tree.js:113:32)

**Test repository:**
- https://github.com/bennyn/typescript-jasmine-karma-nyc/commit/28f1f38dae1a1abdf58f848ff9b378dd95ff3c31

**Comment by LunaPg** [comment]
It's been a year since this issue is open, and I am experiencing this issue with typescript.

**Comment by LunaPg** [comment]
I've found a super weird manipulation to fix the problem !
But I don't have any idea why is works !

1. Generate file 
2. Look at the html file : You 'll have the Cannot rest property error written is covered file
3. Open /.nyc_outpu/processinfo/index
4. generate once more your coverga
5. Open the html file, this time it works fine

So maybe the  .nyc_output file are not properly written, closed or have a problem on permission.

**Comment by godu** [comment]
https://github.com/istanbuljs/nyc/issues/1124#issuecomment-499071658
