### ISSUE TITLE
Coverage Broken: parent.addChild is not a function

### ISSUE THREAD

**Issue by fabriciojso** [istanbuljs/istanbuljs#191]
Run command: `jest --coverage`
Failed to write coverage reports:
        ERROR: TypeError: parent.addChild is not a function
        STACK: TypeError: parent.addChild is not a function
    at /Users/fabriciojso/github/tcc/node_modules/istanbul-lib-report/lib/summarizer.js:181:16
    at Array.forEach (<anonymous>)
    at toDirParents (/Users/fabriciojso/github/tcc/node_modules/istanbul-lib-report/lib/summarizer.js:171:10)
    at Reporter.createPackageSummary [as summarizer] (/Users/fabriciojso/github/tcc/node_modules/istanbul-lib-report/lib/summarizer.js:241:22)
    at Reporter.write (/Users/fabriciojso/github/tcc/node_modules/istanbul-api/lib/reporter.js:81:21)
    at /Users/fabriciojso/github/tcc/node_modules/jest-cli/build/reporters/coverage_reporter.js:181:18
    at Generator.next (<anonymous>)
    at step (/Users/fabriciojso/github/tcc/node_modules/jest-cli/build/reporters/coverage_reporter.js:75:30)
    at /Users/fabriciojso/github/tcc/node_modules/jest-cli/build/reporters/coverage_reporter.js:86:15
    at <anonymous>

**Comment by rodrigooler** [comment]
PR was created with the above problem done by @fabriciojso  https://github.com/istanbuljs/istanbuljs/pull/193

**Comment by coreyfarrell** [comment]
I'm not able to reproduce the error with the linked repository.  I did the following using node.js v10.15.0:
```sh
git clone https://github.com/fabriciojso/monetify-imagini
cd monetify-imagini
npm i
npm t
```
The test `src/core/interface/Application.test.ts` failed but the istanbul reporting seemed to work:
```
--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |    83.58 |    76.47 |    79.17 |    84.85 |                   |
 core/component     |      100 |      100 |      100 |      100 |                   |
  GroupComponent.ts |      100 |      100 |      100 |      100 |                   |
 core/constructor   |      100 |      100 |      100 |      100 |                   |
  Background.ts     |      100 |      100 |      100 |      100 |                   |
  Constructor.ts    |      100 |      100 |      100 |      100 |                   |
  Picture.ts        |      100 |      100 |      100 |      100 |                   |
 core/enum          |      100 |      100 |      100 |      100 |                   |
  Gender.ts         |      100 |      100 |      100 |      100 |                   |
 core/helpers       |    28.57 |        0 |        0 |    30.77 |                   |
  index.ts          |    28.57 |        0 |        0 |    30.77 |... 10,16,17,18,19 |
 facebook           |    90.91 |    66.67 |      100 |    90.91 |                   |
  Facebook.ts       |    90.91 |    66.67 |      100 |    90.91 |                24 |
--------------------|----------|----------|----------|----------|-------------------|
```
