### ISSUE TITLE
Support for `importMeta` in parser for `istanbul-lib-instrument`

### ISSUE THREAD

**Issue by Westbrook** [istanbuljs/istanbuljs#202]
I'm working with code that uses `import.meta.url` syntax with its ESModules, and as such raises the following error when moving through `istanbul-lib-instrument`:
```
SyntaxError: This experimental syntax requires enabling the parser plugin: 'importMeta' (126:15)
    at _class.raise (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:3893:15)
    at _class.expectPlugin (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5227:18)
    at _class.parseImportMetaProperty (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:6364:14)
    at _class.parseExprAtom (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:6152:23)
    at _class.parseExprAtom (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:3594:52)
    at _class.parseExprSubscripts (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5898:21)
    at _class.parseMaybeUnary (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5877:21)
    at _class.parseExprOps (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5786:21)
    at _class.parseMaybeConditional (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5758:21)
    at _class.parseMaybeAssign (/Users/westbrook/Documents/web/repos/wct-istanbub/node_modules/@babel/parser/lib/index.js:5705:21)
```
I'd like to prepare a PR that would add `importMeta` to the plugins, but wanted to ask if it made better sense for the list of plugins to be extendable from the `opts` object instead so that this was less likely to occur again for other syntaxes in the future.

Also, if this is baked in full time, would https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/test/specs/es6-modules.yaml be the right place to add testing for this, or should I add an `import-meta.yaml` series in preparation for other tests in the future?

**Comment by coreyfarrell** [comment]
`istanbul-lib-instrumenter@next` and `nyc@next` now support a `plugins` option which is used to configure babel parser plugins.
