### ISSUE TITLE
Failed to write coverage reports

### ISSUE THREAD

**Issue by joe223** [istanbuljs/istanbuljs#224]
```shell
Failed to write coverage reports:
ERROR: TypeError: Cannot read property 'decl' of undefined
STACK: TypeError: Cannot read property 'decl' of undefined
at /Users/joe/git/Oasis/node_modules/istanbul-reports/lib/lcovonly/index.js:32:38
at Array.forEach (<anonymous>)
at LcovOnlyReport.onDetail (/Users/joe/git/Oasis/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
at LcovReport.(anonymous function) [as onDetail] (/Users/joe/git/Oasis/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
at Visitor.(anonymous function) [as onDetail] (/Users/joe/git/Oasis/node_modules/istanbul-lib-report/lib/tree.js:34:30)
at ReportNode.Node.visit (/Users/joe/git/Oasis/node_modules/istanbul-lib-report/lib/tree.js:123:17)
at /Users/joe/git/Oasis/node_modules/istanbul-lib-report/lib/tree.js:116:23
at Array.forEach (<anonymous>)
at visitChildren (/Users/joe/git/Oasis/node_modules/istanbul-lib-report/lib/tree.js:115:32)
at ReportNode.Node.visit (/Users/joe/git/Oasis/node_modules/istanbul-lib-report/lib/tree.js:126:5)
```
> ./coverage/lcov.info
```
TN:
SF:unknown
```

> ./coverage/coverage-final.json
```json
		"s": {
			"0": 0,
			"1": 0,
			"2": 0,
			"3": 0,
			"4": 0,
			"5": 0,
			"6": 0,
			"7": 0,
			"8": 0,
			"9": 0,
			"10": 0,
			"11": 0,
			"12": 0
		},
		"f": {
			"0": 0
		},
		"b": {
			"0": [
				0,
				0
			]
		},
		"_coverageSchema": "332fd63041d2c1bcb487cc26dd0d5f7d97098a6c",
		"hash": "b2f30def596377432313c9168bee3ee9f2c11d04"
	}
}
```
What I can figure out is `var meta = functionMap[key]` will get `undefined` In this file https://github.com/istanbuljs/istanbuljs/blob/5405550c3868712b14fd8bfe0cbd6f2e7ac42279/packages/istanbul-reports/lib/lcovonly/index.js#L32

So，maybe we should add a conditional statement:
```javascript
    Object.keys(functions).forEach(function (key) {
        var meta = functionMap[key];
        
        if (meta) {
        	writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
        }
    });
```

**Comment by Kosta-Github** [comment]
I am seeing the same issue from time-to-time (almost always on the CI machine), but sometimes also on my local machine, but it is not stable to reproduce; some kind of weird race condition when creating the `function map`?

**Comment by joe223** [comment]
@Kosta-Github I'm no sure there are some differences between `functions` and `functionMap`. 

have we checked this in https://github.com/istanbuljs/istanbuljs/pull/253 ?

**Comment by Kosta-Github** [comment]
for me, this patch fixes exactly the issue you are describing above

**Comment by joe223** [comment]
@Kosta-Github yep，it is！

**Comment by Kosta-Github** [comment]
I am seeing a similar discrepancy between `statement counts` (`s`) and `statementMap` ... see: https://github.com/istanbuljs/istanbuljs/issues/260#issuecomment-453122133

**Comment by DanielRuf** [comment]
Is there a PR to fix this?

**Comment by Kosta-Github** [comment]
I added my findings to #260 but since I am not familiar enough with the internas of the code coverage code I am not able right now to provide a proper fix...

**Comment by abishek-srinivasan** [comment]
I use "ember-cli-code-coverage": "1.0.0-beta.1" and my istanbul-reports version is "^1.5.1". I am able to run the complete test suite. But my coverage/lcov.info is empty. The file is generated but it does not contain any data. When I check my jenkins Codecov, it says, 
Reading reports

    - Skipping empty file ./coverage/lcov.info

--> No coverage data found.

Does anybody have some idea about it?

**Comment by bipiane** [comment]
`npm install source-map-support` works for me.
