### ISSUE TITLE
why is there sometimes a discrepancy between functions and function Map?

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbuljs#260]
sometimes `functions` and `fnMap` do not contain the same keys, let's dig into the relationship between these two data structures.

https://github.com/istanbuljs/istanbuljs/pull/253 CC: @Kosta-Github

**Comment by Kosta-Github** [comment]
@bcoe the `s` counter and the `statementMap` do have the same issue.

I suspect that the issue is within or related to `FileCoverage.prototype.merge`:
https://github.com/istanbuljs/istanbuljs/blob/07724bf6e36803d0377c54b2eb43c3c83b32afe2/packages/istanbul-lib-coverage/lib/file.js#L260-L280

when checking for the condition `Object.keys(other.s).length !== Object.keys(that.data.s).length` and then printing `other` and `that` I can see a discrepancy between the `statementMaps` for both objects at the beginning related to `import` statements for the corresponding source file, e.g.:

`that.statementMap`:
```JSON
{
  "0": { "start": { "line": 10, "column": 25 }, "end": { "line": 10, "column": 30 } },
  "1": { "start": { "line": 18, "column": 8 }, "end": { "line": 18, "column": 77 } },
  ...
}
```
vs `other.statementMap`:
```JSON
{
  "0": { "start": { "line": 1, "column": 0 }, "end": { "line": 1, "column": 45 } },
  "1": { "start": { "line": 3, "column": 0 }, "end": { "line": 3, "column": 35 } },
  "2": { "start": { "line": 4, "column": 0 }, "end": { "line": 4, "column": 34 } },
  "3": { "start": { "line": 5, "column": 0 }, "end": { "line": 5, "column": 31 } },
  "4": { "start": { "line": 6, "column": 0 }, "end": { "line": 6, "column": 39 } },
  "5": { "start": { "line": 8, "column": 0 }, "end": { "line": 8, "column": 65 } },
  "6": { "start": { "line": 10, "column": 25 }, "end": { "line": 10, "column": 30 } },
  "7": { "start": { "line": 18, "column": 8 }, "end": { "line": 18, "column": 77 } },
  ...
}
```
for the source file like this:
```Javascript
import * as MemcachePlus from 'memcache-plus';

import helpers from './_helpers.js';
import config  from './_config.js';
import env     from './_env.js';
import statsd  from './statsd-setup.js';

import { CircuitBreakerFactory } from '@bennadel/circuit-breaker';

const EXTENDED_LOGGING = false;

//////////////////////////////////////////////// InMemoryCache //////////////////////////////////////////////////

// Provide a simple in-memory cache implementation based on Javascript's Map class: https://devdocs.io/javascript/global_objects/map
// It takes the TTLs of the individual entries into account
class InMemoryCache {
    constructor() {
        helpers.debug.warn(`using local in-memory memcached implementation`);

        this.data = new Map();
    }

    async get(key)                  {
        const found = this.data.get(key);
        if (found && (Date.now() >= found.expiry)) { this.data.delete(key); return null; }
        return found ? JSON.parse(found.value) : null;
    }
...
```
the difference between the `statementMaps` is that `that` is skipping the `import` statements whereas `other` contains them in the map and therefore the indices between both maps are off by `6`.

the next difference is in `fnMap`:

`that.fnMap`:
```JSON
{
  "0": {
    "name": "(anonymous_0)",
    "decl": {
      "start": { "line": 17, "column": 4 },
      "end": { "line": 17, "column": 5 }
    },
    "loc": {
      "start": { "line": 17, "column": 18 },
      "end": { "line": 21, "column": 5 }
    },
   "line": 17
  },
  ...
}
```
vs `other.fnMap`:
```JSON
{
  "0": {
    "name": "(anonymous_0)",
    "decl": {
      "start": { "line": 17, "column": 4 },
      "end": { "line": null, "column": -1 }
    },
    "loc": {
     "start": { "line": 17, "column": 4 },
     "end": { "line": 21, "column": 5 }
    }
  },
  ...
}
```
note the `decl.end.line === null` and `decl.end.column === -1`!

I hope, this helps to pinpoint the underlying issue?

**Comment by Kosta-Github** [comment]
I am getting this one now as well:
```
/app/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:52
            line = meta.loc.start.line,
                        ^

TypeError: Cannot read property 'loc' of undefined
    at /app/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:52:25
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/app/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:49:27)
    at LcovReport.(anonymous function) [as onDetail] (/app/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/app/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/app/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:121:17)
    at /app/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:114:23
    at Array.forEach (<anonymous>)
    at visitChildren (/app/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:113:32)
    at ReportNode.Node.visit (/app/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:124:5)
```
which is pointing to: https://github.com/istanbuljs/istanbuljs/blob/f1fb6886cb35093c1a2647c2d602a3dc1fb2fef5/packages/istanbul-reports/lib/lcovonly/index.js#L49-L52
this is again a discrepancy between `branches` and `branchMap` 

we now have discrepancies between:
* `fnMap` & `functions`
* `statements` & `statementMap`
* `branches` & `branchMap`

there seems to be an underlying wrong assumption about the structure of these data structures or the update mechanisms for them

@bcoe are these properties (`fnMap`, `functions`, `statements`, `statementMap`, ...) part of the public API and exposed to other downstream modules?

if not, I would try to merge them pair-wise together...

I am not sure, why these information needs to be split into these pairs?

**Comment by Kosta-Github** [comment]
I am on `istanbul-reports v2.2.4` and still seeing this issue.

I am trying to get code coverage for `typescript` based files and all these discrepancies mentioned above are happing for the `*.ts` or `*.tsx` based files.

Here are differences printed out for the cases where the sizes of `functions` vs. `functionMap` or `branches` vs. `branchMap`, resp. don't match (not sure, if this is helpful in debugging):

```
file:   src/UI/CerealBoxView.tsx: 1 (functionMap) vs. 2 (functions)
functionMap: {"functionMap":{"0":{"name":"(anonymous_0)","decl":{"start":{"line":18,"column":22},"end":{"line":18,"column":23}},"loc":{"start":{"line":18,"column":62},"end":{"line":25,"column":1}},"line":18}}}
functions:   {"functions":{"0":2,"1":null}}

file:  src/UI/CerealBoxView.tsx: 0 (branchMap) vs. 3 (branches)
branchMap: {"branchMap":{}}
branches:  {"branches":{"0":[1,1,1],"1":[1,1],"2":[2,2]}}

file:   src/UI/EditableText.tsx: 1 (functionMap) vs. 2 (functions)
functionMap: {"functionMap":{"0":{"name":"(anonymous_0)","decl":{"start":{"line":14,"column":21},"end":{"line":14,"column":22}},"loc":{"start":{"line":14,"column":39},"end":{"line":34,"column":1}},"line":14}}}
functions:   {"functions":{"0":1,"1":null}}

file:  src/UI/EditableText.tsx: 1 (branchMap) vs. 4 (branches)
branchMap: {"branchMap":{"0":{"loc":{"start":{"line":25,"column":19},"end":{"line":25,"column":30}},"type":"binary-expr","locations":[{"start":{"line":25,"column":19},"end":{"line":25,"column":24}},{"start":{"line":25,"column":28},"end":{"line":25,"column":30}}],"line":25}}}
branches:  {"branches":{"0":[1,1],"1":[0,1],"2":[1,1],"3":[0,0]}}

file:   src/UI/LMVHostComponent.tsx: 2 (functionMap) vs. 3 (functions)
functionMap: {"functionMap":{"0":{"name":"(anonymous_0)","decl":{"start":{"line":8,"column":25},"end":{"line":8,"column":26}},"loc":{"start":{"line":8,"column":49},"end":{"line":21,"column":1}},"line":8},"1":{"name":"(anonymous_1)","decl":{"start":{"line":9,"column":23},"end":{"line":9,"column":24}},"loc":{"start":{"line":9,"column":36},"end":{"line":18,"column":5}},"line":9}}}
functions:   {"functions":{"0":1,"1":107,"2":null}}

file:  src/UI/LMVHostComponent.tsx: 3 (branchMap) vs. 6 (branches)
branchMap: {"branchMap":{"0":{"loc":{"start":{"line":10,"column":8},"end":{"line":17,"column":9}},"type":"if","locations":[{"start":{"line":10,"column":8},"end":{"line":17,"column":9}},{"start":{"line":10,"column":8},"end":{"line":17,"column":9}}],"line":10},"1":{"loc":{"start":{"line":11,"column":12},"end":{"line":13,"column":13}},"type":"if","locations":[{"start":{"line":11,"column":12},"end":{"line":13,"column":13}},{"start":{"line":11,"column":12},"end":{"line":13,"column":13}}],"line":11},"2":{"loc":{"start":{"line":14,"column":12},"end":{"line":16,"column":13}},"type":"if","locations":[{"start":{"line":14,"column":12},"end":{"line":16,"column":13}},{"start":{"line":14,"column":12},"end":{"line":16,"column":13}}],"line":14}}}
branches:  {"branches":{"0":[1,1],"1":[0,1],"2":[1,1],"3":[214,0],"4":[107,107],"5":[107,107]}}
```
`mocha` instrumentation happens via:
```
--require ts-node/register
--require source-map-support/register
```
I would really help to get this resolved, but I am lacking deeper knowledge about `mocha`, `istanbul`, and `nyc` ...

CC: @bcoe

**Comment by coreyfarrell** [comment]
@Kosta-Github if you haven't already could you post a new bug against nyc including all the information requested there?  Without seeing a reproduction I'm wondering if you have `all: true` in your nyc config.  This combined with `--require ts-node/register` being passed to mocha instead of nyc has been shown to cause problems.

**Comment by Kosta-Github** [comment]
yes `all: true` is present in `nyc` config...
so, do you mean by this, I should remove `--require ts-node/register` from the `mocha` config and add it to the `nyc` config instead?

**Comment by coreyfarrell** [comment]
@Kosta-Github yes please give that a try.  This is important because nyc transpiles code to add instrumentation, `ts-node/register` also transpiles.  An issue is that nyc is not being told to require `ts-node/register` when it processes `all: true`, but when you `require('./source-file')` via mocha the source-file is processed by `ts-node/register`.

**Comment by Kosta-Github** [comment]
here is the `envinfo`:
```shell
$ npx envinfo@latest --preset nyc

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 751.23 MB / 16.00 GB
  Binaries:
    Node: 10.16.0 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  npmPackages:
    @babel/core: ^7.4.0 => 7.4.0 
    @babel/plugin-proposal-class-properties: ^7.4.4 => 7.4.4 
    @babel/plugin-proposal-object-rest-spread: ^7.4.0 => 7.4.0 
    @babel/plugin-syntax-dynamic-import: ^7.2.0 => 7.2.0 
    @babel/plugin-transform-runtime: ^7.4.0 => 7.4.0 
    @babel/polyfill: ^7.4.0 => 7.4.0 
    @babel/preset-env: ^7.4.2 => 7.4.2 
    @babel/preset-react: ^7.0.0 => 7.0.0 
    @babel/preset-typescript: ^7.3.3 => 7.3.3 
    @babel/register: ^7.4.0 => 7.4.0 
    babel-eslint: ^10.0.1 => 10.0.1 
    babel-loader: ^8.0.5 => 8.0.5 
    babel-plugin-istanbul: ^5.1.1 => 5.1.1 
    babel-plugin-lodash: ^3.3.4 => 3.3.4 
    babel-plugin-typescript-to-proptypes: ^0.17.1 => 0.17.1 
    nyc: ^14.1.1 => 14.1.1 
    source-map-support: ^0.5.12 => 0.5.12 
    ts-node: ^8.3.0 => 8.3.0 
    typescript: ^3.5.1 => 3.5.2 
```

**Comment by Kosta-Github** [comment]
together with this `mocha` and `nyc` setup:
* `.mocharc.yml`
```yaml
exit: true
require:
  - ts-node/register
  - source-map-support/register
extension:
  - js
  - jsx
  - ts
  - tsx
recursive: true
spec: tests/unit/**/test_*
```
* `.nycrc.json`
```json
{
    "extension": [
        ".js",
        ".jsx",
        ".ts",
        ".tsx"
    ],
    "include": [
        "src/**/*"
    ],
    "exclude": [
        ...
    ],
    "reporter": [
        "lcovonly"
    ],
    "require": [
        "ts-node/register"
    ],
    "all": true,
    "cache": false,
    "sourceMap": false,
    "instrument": true
}
```

**Comment by Kosta-Github** [comment]
so moving `ts-node/register` from `mocha` to `nyc` seems to resolve the crash in the `lcov` reporters... 👍 

but the generated HTML view doesn't look right 👎 , so that I still not trust the generated numbers, e.g.:

![image](https://user-images.githubusercontent.com/2526664/59678422-ac34ad00-91cc-11e9-9177-20ffd4277e8a.png)

**Comment by coreyfarrell** [comment]
You have `sourceMap: false` in your nycrc, could you try setting that true?  Also if source-map is disabled in your tsconfig please enable on that end.  When you get a chance please post your tsconfig.

If enabling sourceMap has no effect please see what happens if you set `all: false` to nyc.  This may help us isolate the issue.

**Comment by Kosta-Github** [comment]
here is the `tsconfig.json`:
```json
{
  "compilerOptions": {
    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": [ "dom", "es2015", "es2016" ],     /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    "jsx": "react",                           /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    // "strict": true,                        /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true,                 /* Enable strict null checks. */
    "strictFunctionTypes": true,              /* Enable strict checking of function types. */
    "strictBindCallApply": true,              /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    "strictPropertyInitialization": true,     /* Enable strict checking of property initialization in classes. */
    "noImplicitThis": true,                   /* Raise error on 'this' expressions with an implied 'any' type. */
    "alwaysStrict": true,                     /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    "noUnusedLocals": true,                   /* Report errors on unused locals. */
    "noUnusedParameters": true,               /* Report errors on unused parameters. */
    "noImplicitReturns": true,                /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true,       /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    "moduleResolution": "node",               /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    "inlineSourceMap": true,                  /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    "experimentalDecorators": true,           /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true             /* Enables experimental support for emitting type metadata for decorators. */
  },
  "include": [ "src", "tests" ]
}
```
so `inlineSourceMap` is `true` for `tsconfig.json`...

1. with `sourceMap: true` the coverage results for the `tsx` files stay the same (as in the screenshot in my previous comment), but for all the `js` & `jsx` files drops to `0%`, e.g.:
![image](https://user-images.githubusercontent.com/2526664/59679592-8ceb4f00-91cf-11e9-8118-94c02011d3dc.png)

2. next try: `sourceMap: true` & `all: false`: coverage results for `tsx` files stays the same (as in the screenshot in my previous comment) and all `js` and `jsx` files got removed (because of their `0%` coverage results)...

3. next try: `sourceMap: false` & `all: false`: is the same result as in my previous comment (`tsx`, `js`, and `jsx` are present), with only the files with `0%` coverage removed.

**Comment by abishek-srinivasan** [comment]
@Kosta-Github I face the exact problem as mentioned above https://github.com/istanbuljs/istanbuljs/issues/260#issuecomment-458928605. Do we have any fix for this. 

I use "ember-cli-code-coverage": "1.0.0-beta.1" and my istanbul-reports version is "^1.5.1"
  
I got this error **Cannot read property 'decl' of undefined** when I tried to run ember coverage-merge command. When I checked out the fix for this, I saw the PR, https://github.com/istanbuljs/istanbuljs/pull/253, where you have replaced functions to functionMap. The code change worked for me but as you have mentioned I got the new error, **Cannot read property 'loc' of undefined** because of discrepancies between branches and branchMap.

Do we have a fix for these discrepancies?

**Comment by Kosta-Github** [comment]
@abishek-srinivasan no (not yet)

I am waiting for a new major release of `nyc@15` with hopefully improved `TypeScript` support

**Comment by coreyfarrell** [comment]
nyc 15.0.0 is released and fixes a major cause of this issue for nyc.

**Comment by ColCh** [comment]
I am on istanbul-reports@3.0.2, nyc@15.0.1 and using no mocha but I'm facing this issue

coverage is reported just right, but html reporter throws an error on this line

https://github.com/istanbuljs/istanbuljs/blob/1b52fe750d1f800c34dbff168614c0c73bd76026/packages/istanbul-reports/lib/html/annotator.js#L89

Error stack:

```
Cannot read property 'decl' of undefined
TypeError: Cannot read property 'decl' of undefined
    at Object.entries.forEach (/foo/bar/node_modules/istanbul-reports/lib/html/annotator.js:89:31)
    at Array.forEach ()
    at annotateFunctions (/foo/bar/node_modules/istanbul-reports/lib/html/annotator.js:86:29)
    at annotateSourceCode (/foo/bar/node_modules/istanbul-reports/lib/html/annotator.js:234:9)
    at HtmlReport.onDetail (/foo/bar/node_modules/istanbul-reports/lib/html/index.js:409:33)
    at HtmlSpaReport.onDetail (/foo/bar/node_modules/istanbul-reports/lib/html-spa/index.js:93:25)
    at Visitor.value (/foo/bar/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/foo/bar/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at getChildren.forEach.child (/foo/bar/node_modules/istanbul-lib-report/lib/tree.js:92:19)
    at Array.forEach ()

```

**Comment by coreyfarrell** [comment]
Please post a link to a repository demonstrating this issue.  I suspect any remaining occurrences of this issue are caused by something other than istanbul-lib-instrument@4.x generating the coverage data.

**Comment by ColCh** [comment]
I have only one instanbul-lib-instrument version in my repo:

```
[1/4] Why do we have the module "istanbul-lib-instrument"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "istanbul-lib-instrument@4.0.3"
info Reasons this module exists
   - "nyc" depends on it
   - Hoisted from "nyc#istanbul-lib-instrument"
   - Hoisted from "@jsdevtools#coverage-istanbul-loader#istanbul-lib-instrument"
info Disk size without dependencies: "18.05MB"
info Disk size with unique dependencies: "24.63MB"
info Disk size with transitive dependencies: "49.07MB"
info Number of shared dependencies: 36
```

Will try to make small repo to reproduce this issue

**Comment by TheTrio** [comment]
Thank you so much! Switching to the babel fixed the issue.
