### ISSUE TITLE
HTML reporter: Cannot read property 'locations' of undefined

### ISSUE THREAD

**Issue by jviotti** [istanbuljs/istanbuljs#413]
Hey there! We have a setup where we are getting code coverage from server side code tested through Ava, and also front-end JSX/React code through Puppeteer. We're doing the latter by instrumenting the bundle, running Puppeteer, evaluating the contents of `window._coverage__`, saving the results into `.nyc_output` and finally doing an `nyc report` using the HTML reporter.

Everything seems fine, except that we see the following in some of the UI files:

<img width="917" alt="Screenshot 2019-05-29 at 13 25 34" src="https://user-images.githubusercontent.com/2192773/58557014-3ebcde80-8215-11e9-9dde-beae75f187bd.png">

Notice only some few files have this problem. We have examples of JSX files that work fine.

What would be the best way to attempt to debug this further?

- nyc: 14.1.1
- istanbul-lib-coverage: 2.0.5
- istanbul-lib-hook: 2.0.7
- istanbul-lib-instrument: 3.3.0
- istanbul-lib-report: 2.0.8
- istanbul-lib-source-maps: 3.0.6
- istanbul-reports: 2.2.6

**Comment by jviotti** [comment]
I isolated the problem to two JSON files inside `.nyc_output`: https://gist.github.com/jviotti/02de2359cefcf1642e9d0a83240996d5. Generating the HTML report with these two files triggers the issue on that file, but leaving aside either of them makes it work.

I sadly can't share the corresponding source code from my employer.

**Comment by jviotti** [comment]
The source code the error is pointing at `node_modules/istanbul-reports/lib/html/annotator.js:131:50` is the last line of this snippet:

```js
function annotateBranches(fileCoverage, structuredText) {
    const branchStats = fileCoverage.b;
    const branchMeta = fileCoverage.branchMap;
    if (!branchStats) {
        return;
    }

    Object.keys(branchStats).forEach(branchName => {
        const branchArray = branchStats[branchName];
        const sumCount = branchArray.reduce((p, n) => p + n, 0);
        const metaArray = branchMeta[branchName].locations;
```

**Comment by jviotti** [comment]
This is `branchMeta` at the point of failure:

```json
{
  "0": {
    "loc": {
      "start": {
        "line": 46,
        "column": 4
      },
      "end": {
        "line": 48,
        "column": 5
      }
    },
    "type": "if",
    "locations": [
      {
        "start": {
          "line": 46,
          "column": 4
        },
        "end": {
          "line": 48,
          "column": 5
        }
      },
      {
        "start": {
          "line": 46,
          "column": 4
        },
        "end": {
          "line": 48,
          "column": 5
        }
      }
    ],
    "line": 46
  },
  "1": {
    "loc": {
      "start": {
        "line": 46,
        "column": 8
      },
      "end": {
        "line": 46,
        "column": 37
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 46,
          "column": 8
        },
        "end": {
          "line": 46,
          "column": 27
        }
      },
      {
        "start": {
          "line": 46,
          "column": 31
        },
        "end": {
          "line": 46,
          "column": 37
        }
      }
    ],
    "line": 46
  },
  "2": {
    "loc": {
      "start": {
        "line": 60,
        "column": 13
      },
      "end": {
        "line": 60,
        "column": 46
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 60,
          "column": 13
        },
        "end": {
          "line": 60,
          "column": 22
        }
      },
      {
        "start": {
          "line": 60,
          "column": 26
        },
        "end": {
          "line": 60,
          "column": 35
        }
      },
      {
        "start": {
          "line": 60,
          "column": 39
        },
        "end": {
          "line": 60,
          "column": 46
        }
      }
    ],
    "line": 60
  },
  "3": {
    "loc": {
      "start": {
        "line": 65,
        "column": 49
      },
      "end": {
        "line": 65,
        "column": 71
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 65,
          "column": 49
        },
        "end": {
          "line": 65,
          "column": 62
        }
      },
      {
        "start": {
          "line": 65,
          "column": 66
        },
        "end": {
          "line": 65,
          "column": 71
        }
      }
    ],
    "line": 65
  },
  "4": {
    "loc": {
      "start": {
        "line": 79,
        "column": 20
      },
      "end": {
        "line": 81,
        "column": 14
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 79,
          "column": 20
        },
        "end": {
          "line": 81,
          "column": 6
        }
      },
      {
        "start": {
          "line": 81,
          "column": 10
        },
        "end": {
          "line": 81,
          "column": 14
        }
      }
    ],
    "line": 79
  },
  "5": {
    "loc": {
      "start": {
        "line": 92,
        "column": 3
      },
      "end": {
        "line": 94,
        "column": 4
      }
    },
    "type": "if",
    "locations": [
      {
        "start": {
          "line": 92,
          "column": 3
        },
        "end": {
          "line": 94,
          "column": 4
        }
      },
      {
        "start": {
          "line": 92,
          "column": 3
        },
        "end": {
          "line": 94,
          "column": 4
        }
      }
    ],
    "line": 92
  },
  "6": {
    "loc": {
      "start": {
        "line": 92,
        "column": 7
      },
      "end": {
        "line": 92,
        "column": 45
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 92,
          "column": 7
        },
        "end": {
          "line": 92,
          "column": 26
        }
      },
      {
        "start": {
          "line": 92,
          "column": 30
        },
        "end": {
          "line": 92,
          "column": 45
        }
      }
    ],
    "line": 92
  },
  "7": {
    "loc": {
      "start": {
        "line": 118,
        "column": 23
      },
      "end": {
        "line": 120,
        "column": 13
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 118,
          "column": 23
        },
        "end": {
          "line": 120,
          "column": 5
        }
      },
      {
        "start": {
          "line": 120,
          "column": 9
        },
        "end": {
          "line": 120,
          "column": 13
        }
      }
    ],
    "line": 118
  },
  "8": {
    "loc": {
      "start": {
        "line": 158,
        "column": 10
      },
      "end": {
        "line": 158,
        "column": 92
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 158,
          "column": 10
        },
        "end": {
          "line": 158,
          "column": 36
        }
      },
      {
        "start": {
          "line": 158,
          "column": 40
        },
        "end": {
          "line": 158,
          "column": 92
        }
      }
    ],
    "line": 158
  },
  "9": {
    "loc": {
      "start": {
        "line": 177,
        "column": 11
      },
      "end": {
        "line": 177,
        "column": 33
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 177,
          "column": 11
        },
        "end": {
          "line": 177,
          "column": 20
        }
      },
      {
        "start": {
          "line": 177,
          "column": 24
        },
        "end": {
          "line": 177,
          "column": 33
        }
      }
    ],
    "line": 177
  },
  "10": {
    "loc": {
      "start": {
        "line": 180,
        "column": 2
      },
      "end": {
        "line": 182,
        "column": 3
      }
    },
    "type": "if",
    "locations": [
      {
        "start": {
          "line": 180,
          "column": 2
        },
        "end": {
          "line": 182,
          "column": 3
        }
      },
      {
        "start": {
          "line": 180,
          "column": 2
        },
        "end": {
          "line": 182,
          "column": 3
        }
      }
    ],
    "line": 180
  },
  "11": {
    "loc": {
      "start": {
        "line": 184,
        "column": 19
      },
      "end": {
        "line": 184,
        "column": 55
      }
    },
    "type": "cond-expr",
    "locations": [
      {
        "start": {
          "line": 184,
          "column": 30
        },
        "end": {
          "line": 184,
          "column": 43
        }
      },
      {
        "start": {
          "line": 184,
          "column": 46
        },
        "end": {
          "line": 184,
          "column": 55
        }
      }
    ],
    "line": 184
  },
  "12": {
    "loc": {
      "start": {
        "line": 185,
        "column": 28
      },
      "end": {
        "line": 188,
        "column": 10
      }
    },
    "type": "cond-expr",
    "locations": [
      {
        "start": {
          "line": 185,
          "column": 45
        },
        "end": {
          "line": 188,
          "column": 3
        }
      },
      {
        "start": {
          "line": 188,
          "column": 6
        },
        "end": {
          "line": 188,
          "column": 10
        }
      }
    ],
    "line": 185
  },
  "13": {
    "loc": {
      "start": {
        "line": 187,
        "column": 10
      },
      "end": {
        "line": 187,
        "column": 52
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 187,
          "column": 10
        },
        "end": {
          "line": 187,
          "column": 29
        }
      },
      {
        "start": {
          "line": 187,
          "column": 33
        },
        "end": {
          "line": 187,
          "column": 52
        }
      }
    ],
    "line": 187
  },
  "14": {
    "loc": {
      "start": {
        "line": 206,
        "column": 6
      },
      "end": {
        "line": 246,
        "column": 6
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 206,
          "column": 6
        },
        "end": {
          "line": 206,
          "column": 25
        }
      },
      {
        "start": {
          "line": 207,
          "column": 6
        },
        "end": {
          "line": 245,
          "column": 32
        }
      }
    ],
    "line": 206
  },
  "15": {
    "loc": {
      "start": {
        "line": 249,
        "column": 5
      },
      "end": {
        "line": 289,
        "column": 5
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 249,
          "column": 5
        },
        "end": {
          "line": 249,
          "column": 18
        }
      },
      {
        "start": {
          "line": 250,
          "column": 5
        },
        "end": {
          "line": 288,
          "column": 13
        }
      }
    ],
    "line": 249
  },
  "16": {
    "loc": {
      "start": {
        "line": 262,
        "column": 9
      },
      "end": {
        "line": 262,
        "column": 95
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 262,
          "column": 9
        },
        "end": {
          "line": 262,
          "column": 37
        }
      },
      {
        "start": {
          "line": 262,
          "column": 42
        },
        "end": {
          "line": 262,
          "column": 66
        }
      },
      {
        "start": {
          "line": 262,
          "column": 70
        },
        "end": {
          "line": 262,
          "column": 94
        }
      }
    ],
    "line": 262
  },
  "17": {
    "loc": {
      "start": {
        "line": 264,
        "column": 8
      },
      "end": {
        "line": 273,
        "column": 8
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 264,
          "column": 8
        },
        "end": {
          "line": 264,
          "column": 34
        }
      },
      {
        "start": {
          "line": 265,
          "column": 8
        },
        "end": {
          "line": 272,
          "column": 17
        }
      }
    ],
    "line": 264
  },
  "18": {
    "loc": {
      "start": {
        "line": 266,
        "column": 16
      },
      "end": {
        "line": 266,
        "column": 67
      }
    },
    "type": "cond-expr",
    "locations": [
      {
        "start": {
          "line": 266,
          "column": 37
        },
        "end": {
          "line": 266,
          "column": 60
        }
      },
      {
        "start": {
          "line": 266,
          "column": 63
        },
        "end": {
          "line": 266,
          "column": 67
        }
      }
    ],
    "line": 266
  },
  "19": {
    "loc": {
      "start": {
        "line": 270,
        "column": 62
      },
      "end": {
        "line": 270,
        "column": 86
      }
    },
    "type": "binary-expr",
    "locations": [
      {
        "start": {
          "line": 270,
          "column": 62
        },
        "end": {
          "line": 270,
          "column": 72
        }
      },
      {
        "start": {
          "line": 270,
          "column": 76
        },
        "end": {
          "line": 270,
          "column": 86
        }
      }
    ],
    "line": 270
  }
}
```

And `branchName` is `'20'`

**Comment by jviotti** [comment]
Given that this happens when only both files are present I imagine there is an off by one bug somewhere when merging the JSONs inside `.nyc_output`

**Comment by dvail** [comment]
I'm getting an almost identical issue when merging reports generated from Jest and puppeteer-to-istanbul via page.coverage.stopJSCoverage().

This occurs as described above in the `html` report as well as the `lcov` one. Stepping through the istanbul source I can see there is a mismatch between the length of `branches` and `branchMap` here: https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/lcovonly/index.js#L50

I'm not very familiar with this code yet, but it seems like the problem is related to the one described in this issue: https://github.com/istanbuljs/istanbuljs/issues/260

**Comment by dvail** [comment]
To add onto that I'm not using Typescript/JSX/Webpack, these are all native html imported JS files when being tested through puppeteer. On the Jest side though I am using `babel-jest` to be able to use the `import` keyword, possibly leading to the mismatch?

**Comment by KnisterPeter** [comment]
I have the same problem with the lcovonly reporter.
It seems only happen when I enable `all` and it seems to be a race-condition since on 10 executions it happens only x times.

I'm using mocha + typescript.

Not sure if its the same error but in my case this is the error trace:

```shell
/home/markusw/source/tsdi/node_modules/istanbul-reports/lib/lcovonly/index.js:52
        const line = meta.loc.start.line;
                          ^

TypeError: Cannot read property 'loc' of undefined
    at /home/markusw/source/tsdi/node_modules/istanbul-reports/lib/lcovonly/index.js:52:27
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/home/markusw/source/tsdi/node_modules/istanbul-reports/lib/lcovonly/index.js:49:27)
    at Visitor.<computed> [as onDetail] (/home/markusw/source/tsdi/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/markusw/source/tsdi/node_modules/istanbul-lib-report/lib/tree.js:114:17)
    at /home/markusw/source/tsdi/node_modules/istanbul-lib-report/lib/tree.js:118:15
    at Array.forEach (<anonymous>)
    at ReportNode.Node.visit (/home/markusw/source/tsdi/node_modules/istanbul-lib-report/lib/tree.js:117:24)
    at Tree.visit (/home/markusw/source/tsdi/node_modules/istanbul-lib-report/lib/tree.js:150:20)
    at /home/markusw/source/tsdi/node_modules/nyc/index.js:408:12

```

**Comment by TheTrio** [comment]
For me, switching to [`babel-plugin-istanbul`](https://github.com/istanbuljs/babel-plugin-istanbul) seems to have fixed the issue. 

More: https://github.com/istanbuljs/istanbuljs/issues/260

**Comment by jviotti** [comment]
Closing stale issues
