### ISSUE TITLE
Class properties filing to parse

### ISSUE THREAD

**Issue by RIAEvangelist** [istanbuljs/istanbuljs#509]
my coverage still fails on this

```
   class Defaults{
        appspace = 'app.';
   }

```

```

Failed to parse file: C:\Users\diginow\Documents\code\git\node-ipc\entities\Defaults.js
Transformation error; return original code
Error: Line 7: Unexpected token =
    at constructError (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:2407:21)
    at createError (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:2426:17)
    at unexpectedTokenError (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:2500:13)
    at throwUnexpectedToken (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:2505:15)
    at parseFunctionSourceElements (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:4869:23)
    at parseFunctionExpression (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:5074:16)
    at parsePrimaryExpression (C:\Users\diginow\Documents\code\git\node-ipc\node_modules\esprima\esprima.js:3273:24) {
  lineNumber: 7,
  description: 'Unexpected token =',
  index: 93
}


```

Seems the ES6 Class property syntax is not supported, any suggestions for this?

**Comment by coreyfarrell** [comment]
esprima is not a dependency of nyc or the current istanbul-* libraries.  It was a dependency of the deprecated and unsupported `istanbul` library.

If you are using the `istanbul` module for code coverage then the suggestion is to either switch to nyc or check out https://istanbul.js.org/integrations for alternatives.  The current version of nyc has support for class properties.
