### ISSUE TITLE
html report broken in early Node 13.x runtime

### ISSUE THREAD

**Issue by panva** [istanbuljs/istanbuljs#550]
`html-escaper` 2.0.1 released `2020-3-21` breaks `istanbul-reports` html reporter on early Node.js 13.x runtime versions (e.g. 13.0.0).

The [change](https://github.com/webreflection/html-escaper/compare/v2.0.0...v2.0.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) results in a throw [here](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/index.js#L13) which then continues on to trigger e.g. `require('lcov')` which also fails.

Below is the original swallowed error.

```
Error: Package exports for '/Users/panva/repo/ultimate-jose/node_modules/html-escaper' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:414:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:487:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:782:27)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/panva/repo/ultimate-jose/node_modules/istanbul-reports/lib/html/index.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32) {
```

May I suggest to lock down the `html-escaper` dependency version to 2.0.0 to stop the countless CI failures we're seeing across the board in our projects?

**Comment by panva** [comment]
Resolved in https://github.com/WebReflection/html-escaper/issues/1

`istanbul-reports` should stick to `html-escaper@2.0.0` or `2.0.2`

2.0.1 and 3.x cannot be required on node 13.0.0 13.0.1 and 13.1.0

**Comment by coreyfarrell** [comment]
istanbul-reports will hold back the dependency to `^2.0.0` until the next semver-major.  Note I'm not performing a new release to specifically block html-escaper@2.0.1, if you have any projects with a lockfile you will need to regenerate the lockfile to pull in html-escaper@2.0.2.

Also be aware that the next semver-major of istanbul-reports will bump all dependencies so 13.0.x and 13.1.0 will break at that point (this will be after 13.x is EOL).
