### ISSUE TITLE
Improve support for "shebang" scripts

### ISSUE THREAD

**Issue by RobinKnipe** [istanbuljs/istanbuljs#578]
Currently when the `/lib/hook.js` utility loads a file a SyntaxError is thrown if the target file is a shell script that includes a shebang line, i.e.
```
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:1040:15)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.Module._extensions.<computed> [as .js] (/app/node_modules/istanbul/lib/hook.js:109:37)
```

Node version: `12.18.3`
Docker containers: `node:12`, `node:12-alpine`

Is this a regression that has happened recently? Istanbul was providing test coverage for the same code without issue previously.

**Comment by coreyfarrell** [comment]
To my knowledge this is (or was) a change in node.js, not nyc.  Does your file have a byte order mark?  If so that is not valid and is no longer tolerated by node.js.

**Comment by RobinKnipe** [comment]
Hi @coreyfarrell - no - this was one of the things that I checked having found little other information while searching the problem at length.

**Comment by coreyfarrell** [comment]
A small demonstration in a git repository would be useful.  I just tested by creating script.cjs:
```js
#!/usr/bin/env node
console.log('hello');
```

The following worked:
```
chmod +x script.cjs
./script.cjs && npx nyc ./script.cjs
```

In the nyc case the script displayed coverage.  This also worked when I had another script `require(./script.cjs')`.  I tested in node.js 14.15.1 with nyc 15.1.0.
