### ISSUE TITLE
Running jest with --verbose causes error in istanbul-lib-coverage

### ISSUE THREAD

**Issue by jolting** [istanbuljs/istanbuljs#632]
The strange thing is that I can run without verbose and it doesn't show this error, but adding --verbose in jest causes this error.
```
  ● Test suite failed to run

    TypeError: Cannot read property 'locations' of undefined

      at keyFromLocationsProp (node_modules/istanbul-lib-coverage/lib/file-coverage.js:220:56)
      at node_modules/istanbul-lib-coverage/lib/file-coverage.js:49:15
          at Array.reduce (<anonymous>)
      at mergeProp (node_modules/istanbul-lib-coverage/lib/file-coverage.js:47:41)
      at FileCoverage.merge (node_modules/istanbul-lib-coverage/lib/file-coverage.js:232:23)
      at CoverageMap.addFileCoverage (node_modules/istanbul-lib-coverage/lib/coverage-map.js:112:29)
      at node_modules/istanbul-lib-coverage/lib/coverage-map.js:55:18
          at Array.forEach (<anonymous>)
      at CoverageMap.merge (node_modules/istanbul-lib-coverage/lib/coverage-map.js:54:35)
      at CoverageReporter.onTestResult (node_modules/@jest/reporters/build/CoverageReporter.js:226:25)
   ```
I was wondering if I'm doing something wrong.

**Comment by bcoe** [comment]
@JustinChristensen this looks like this is potentially cropping up in the new merging logic, does anything jump out at you?

**Comment by JustinChristensen** [comment]
@bcoe it's the same thing as that other issue. The new merge logic expects an invariant to hold that doesn't seem to be holding in some cases (that there will be an equal number of corresponding keys between properties like `s` and `statementMap`. I gave more background on this in that other issue. Might be time to roll back until someone can dig into this.

**Comment by bcoe** [comment]
@JustinChristensen 👍 thanks for response.

**Comment by bcoe** [comment]
@jolting I believe `v3.0.2` should fix the issue, mind letting me know?
