### ISSUE TITLE
[istanbul-lib-coverage] Don't know how to turn this value into a node

### ISSUE THREAD

**Issue by LukasKlement** [istanbuljs/istanbuljs#646]
The istanbul-lib-coverage library throws this error when instrumenting code in combination with Angular 12.2.10:

/src/main.ts: don't know how to turn this value into a node
(excluding this file it progressively shows the same error for polyfills.ts, environment.ts, etc.)

The error does not occur with Angular 12.2.9. Is this something that should be fixed downstream? If so, what triggers this error?

Here's the full stacktrace:

```./src/main.ts - Error: Module build failed (from ./node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js):
Error: /Users/mypath/src/main.ts: don't know how to turn this value into a node
    at valueToNode (/Users/mypath/node_modules/@babel/types/lib/converters/valueToNode.js:98:9)
    at Object.valueToNode (/Users/mypath/node_modules/@babel/types/lib/converters/valueToNode.js:92:58)
    at Object.exit (/Users/mypath/node_modules/istanbul-lib-instrument/dist/visitor.js:641:30)
    at PluginPass.exit (/Users/mypath/node_modules/istanbul-lib-instrument/dist/instrumenter.js:104:29)
    at newFn (/Users/mypath/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/mypath/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/mypath/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/mypath/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/Users/mypath/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/mypath/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/Users/mypath/node_modules/@babel/traverse/lib/context.js:131:19)
    at Function.traverse.node (/Users/mypath/node_modules/@babel/traverse/lib/index.js:82:17)
    at traverse (/Users/mypath/node_modules/@babel/traverse/lib/index.js:62:12)
    at transformFile (/Users/mypath/node_modules/@babel/core/lib/transformation/index.js:105:29)
    at transformFile.next (<anonymous>)
    at run (/Users/mypath/node_modules/@babel/core/lib/transformation/index.js:33:12)
    at run.next (<anonymous>)
    at transform (/Users/mypath/node_modules/@babel/core/lib/transform.js:25:41)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/mypath/node_modules/gensync/index.js:251:28)
    at sync (/Users/mypath/node_modules/gensync/index.js:89:14)
    at Instrumenter.instrumentSync (/Users/mypath/node_modules/istanbul-lib-instrument/dist/instrumenter.js:112:45)
```

The webpack configuration is as follows:

```module.exports = {
  module: {
    rules: [
      {
        test: /\.(js|ts)$/,
        loader: '@jsdevtools/coverage-istanbul-loader',
        options: { esModules: true },
        enforce: 'post',
        include: require('path').join(__dirname, '..', 'src'),
        exclude: [
          /\.(e2e|spec)\.ts$/,
          /node_modules/,
          /(ngfactory|ngstyle)\.js/,
        ],
      },
    ],
  },
};
```

**Comment by divdavem** [comment]
> @angular/core@12.2.11 / @angular/material@12.2.11 fixed the bug, I'd say we can close this issue despite not having identified the culprit.

For those who come here and are interested in identifying "the culprit", here it is: https://github.com/angular/angular-cli/issues/21967
