### ISSUE TITLE
New design for HTML report

### ISSUE THREAD

**Issue by J-Sek** [istanbuljs/istanbuljs#69]
Some time ago I created ["hacky" way](https://github.com/J-Sek/istanbul-coverage-report-extensions) of getting some UX improvements to HTML Istanbul report. I would love to make these improvements available to all developers, so I plan to port them (or just a part we agree on) to Istanbul source.

Would be great if you could let me know if you like this idea or not, so I can proceed with preparing clean implementation. :)

Please check [live demo](http://istanbul-report-demo.surge.sh) I managed to generate for Istanbul sources.

Problems with current design:

- hard to read, flat list, noisy design
- navigation between static pages, loosing context

New design:

- tree structure
- opening file coverage in modal dialog
- summary chart with meaningful info/warning

Known issues/limitations of current implementation:

- iziModal behavior when displaying report in iframe
- missing routing (cannot share link to an open modal)
- report should rather be served on the server in order to fetch all pages

**Comment by bcoe** [comment]
@J-Sek wow, this is pretty darn slick! I'm a bit slammed this week with work at npm -- but am really digging this.

I'm definitely open to redesign, curious to hear other's thoughts (CC: @gotwarlost, @isaacs).

**Comment by isaacs** [comment]
The modal iframe doesn't seem to work so well on small iOS screens. I'll take a look at it on a bigger device in the next few days.

**Comment by isaacs** [comment]
Ok, looked on a larger screen.

There are some aspects of this I like, and some I definitely don't.

Like:

1. The full tree is nice.  Clicking through separate pages per-folder is kind of tedious.
2. I can see how sorting files by coverage is super handy.

Don't like:

1. WAY too much motion.  It's distracting for me, and probably will cause nausea or dizziness in anyone with certain vision and/or vestibular issues.
2. The model feels pretty klunky.  I'd actually be ok with a frameset, but having two scrollable windows overlaid on one another such that a single scroll action can cause unpredictable effects is very weird to me.
3. When sorting by anything other than filename, the folder structure is completely lost.
4. I don't like saying "there's a x% chance that you won't notice broken logic".  I frequently write bugs in 100% test covered code.  There is a 100% chance that a program has broken logic.
5. Sometimes sorting by coverage levels makes the whole file list disappear:

    ```
    TypeError: Cannot read property 'options' of undefined
        at iziModal.min.js:1
        at dispatch (jquery-3.1.0.min.js:3)
        at q.handle (jquery-3.1.0.min.js:3)
    sorter.js:75 Uncaught TypeError: Cannot read property 'branches' of undefined
        at sorter (http://istanbul-report-demo.surge.sh/sorter.js:75:27)
        at finalSorter (http://istanbul-report-demo.surge.sh/sorter.js:86:29)
        at Array.sort (native)
        at sortByIndex (http://istanbul-report-demo.surge.sh/sorter.js:95:14)
        at HTMLTableCellElement.<anonymous> (http://istanbul-report-demo.surge.sh/sorter.js:126:21)
    ```

**Comment by J-Sek** [comment]
Thanks for the feedback :) Hard to get one even in my company, where I introduced it few months ago.

So the sorting is definitely a concern, although I hardly remember to ever use it. I left it broken, because I felt like there will be a better time to address this when I will implement it the _clean_ way.

I haven't try this on mobile (iPhone or Android tablet) until you pointed out some issues on smaller screen. I saw the modal is in fact unpredictable, so I will try to find a better component or simply fallback to page reload.

The summary with chart is based on some first idea that came to my head when I tried to make it "speak" to the reader something meaningful, _consumable_ at first glance. I agree it will be better to change the message and I already suppressed the animation for the [demo](http://istanbul-report-demo.surge.sh). If you have any better idea for top section, please don't hesitate to share :)

**Comment by emilsedgh** [comment]
This seems real nice. Specially the tree view. Good job.

I think the widget at top is wasting a top of space though. It can be improved I think.

**Comment by bcoe** [comment]
@J-Sek sorry for the very slow feedback!

I echo @isaacs' feedback:

* _regarding motion_, perhaps we could just disable some of the transitions taking place, e.g., sliding in the filename when you open a report.
* _regarding missing file listing when sorting_, this just seems like a bug we'd need to address.
* _regarding inspirational message about % of coverage_, I like the encouragement it provides, but to @isaacs' point we shouldn't guarantee your code is stable because you have great coverage.

Regarding @emilsedgh's feedback:

I like the widget that provides feedback about overall coverage, but it does take up a lot of vertical space, maybe we could simply flatten it a bit (make it a rectangle sitting on top of the file file listing?).

## what next?

* we should definitely make sure things work well on mobile before landing.
* I'm a little worried about how much bulk this might add to the `istanbul-report` module:
  * what's the total footprint size of this new design with it's JavaScript and CSS; and what's the licensing of the libraries you're using, e.g., the pie-chart, we should make sure this is MIT or ISC or some equivalent.
  * worst case scenario, perhaps we could make it so this new "modern HTML" report can be installed as a dependency.
  * regardless of whether we bundle this new report (or provide it as an optional installation, with documentation in Istanbul) I think we should introduce the report with a new name, perhaps something like `html-modern` or `html-single-page`? This would allow people to start playing with the new HTML report while we hammer out any additional bugs.

**Comment by Gidgidonihah** [comment]
I'll throw in my 2 cents on this topic. I would love to have a more modern looking report. This is a good start. 

## Here are my criticisms (some of which were already covered):
* **the "chance" statement is misleading.** I do like the chart above it though.
* **Initial view is harder to grok.** starting with more than 1 level deep open seems cluttered. Perhaps offer a way to expand the tree all at once either at the root, or any given point.
* **context is lost on page reload.** If I'm working an a specific folder, I run my report and reload to see the changes, my expanded path is gone. As is the modal with any file I had open.
* **CMD/CTRL + click should still open a file in a new tab/window.** As is, I have to right click on the file link and choose open in new tab/window
* **Stats/metadata about a file are missing.** After clicking on a file, the modal pops up and has the path, but all the stats about the coverage of the particular file is gone. If I open the file in a new tab/window I don't even have the path visible. 

## And here are what I assume are bugs:
* Clicking on any sort makes all files disappear for me.
* Opening and closing a folder is inconsistent. I only tried `packages`, but sometimes when it opens, all the folders below it are closes. Sometimes they are open. I haven't seen a pattern on why.

## My wish list
I have always found the visuals of the current html report a bit grating. Especially the code page. It's functional as is, and the old saying goes "If it ain't broke...", but I'd like to implement a softer look. I took a look at a few reporters such as codecov, codeclimate and coveralls. I'm partial to some of the things that coveralls.io does. 

I'd be happy to provide some mockups before the work is put in. When I made a few changes for #88 I realized that due to the way it is currently laid out, making the changes I'm talking about here would require a non-negligable change to the structure.

**Comment by lukeapage** [comment]
I might take a shot at a Pr to implement some of this, but not the whole shebang. I’m interested in:

Tree view - presumably as an option 
Sorting- maybe a small inline custom js (no libs)
Option to choose what to report (branches, lines, statements, functions)

**Comment by lukeapage** [comment]
Okay I learnt two non-obvious things.

1. there is sorting, its just there are no styles to indicate it
2. you can configure the summary type to either be a) a tree b) folders c) flat
It would be kind of nice to switch between those in one report though.
